version: '2'

services:
  poaa:
    build:
      context: ./docker
      args:
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    command: yarn start
    working_dir: /app
    tty: true
    environment:
    - LOCAL_USER_ID
    ports:
    - 3000:3000
    volumes:
    - .:/app:delegated
    - home:/home/node

volumes:
  home:
